[package]
name = "boxes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.0"
bevy_easings = "0.8.1"
itertools = "0.10.3"
rand = "0.8.5"
